### ISSUE TITLE
uSync doesn't like null values on import (VortoContentMapper)

### ISSUE THREAD

**Issue by netaddicts** [KevinJump/uSync3.0#108]
Ran into issue while trying to save a document that has a vorto property wrapping an rte.

Repro path:
If you don't enter any text in any of the rte tabs, a null value gets stored in umbraco.config, hence uSync tries to derialize the value from json to an object but fails

Log entries
```
2017-01-11 17:37:55,078 [P12532/D5/T159] INFO  Jumoo.uSync.Content.ContentHandler - Content Save Fired:
 2017-01-11 17:37:55,078 [P12532/D5/T159] DEBUG Jumoo.uSync.Core.Serializers.ContentSerializer - Serialize Core: test
 2017-01-11 17:37:55,078 [P12532/D5/T159] DEBUG Jumoo.uSync.Core.Events - Mapping Content Export: Our.Umbraco.Vorto Custom
 2017-01-11 17:37:55,083 [P12532/D5/T159] DEBUG Jumoo.uSync.ContentMappers.VortoContentMapper - Vorto: {"values":null,"dtdGuid":"683d69d3-00d1-4ad2-89ae-f5499ad68144"}
 2017-01-11 17:37:55,083 [P12532/D5/T159] WARN  Jumoo.uSync.Content.ContentHandler - Error saving Content: System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at Jumoo.uSync.ContentMappers.VortoContentMapper.MapVortoValues(Int32 dataTypeDefinitionId, String value, Boolean import)
   at Jumoo.uSync.Core.Serializers.ContentBaseSerializer`1.GetExportIds(PropertyType propType, XElement value)
   at Jumoo.uSync.Core.Serializers.ContentBaseSerializer`1.SerializeBase(IContentBase item, String contentTypeAlias)
   at Jumoo.uSync.Core.Serializers.ContentSerializer.SerializeCore(IContent item)
   at Jumoo.uSync.Content.ContentHandler.ExportItem(IContent item, String path, String rootFolder)
```

I'll fork and change the code tomorrow and send a pr afterwards.

Affected line: https://github.com/KevinJump/uSync/blob/Dev-v7_4/Jumoo.uSync.ContentMappers/VortoContentMapper.cs#L58

**Comment by KevinJump** [comment]
thanks, i will roll this into the next patch release and push it out (prob next week)

**Comment by netaddicts** [comment]
:+1: Looking forward to the release!
