### ISSUE TITLE
Export failing on multinode treepickers in 7.5.13 with newtonsoft v. 8

### ISSUE THREAD

**Issue by Ladefuss** [KevinJump/uSync3.0#136]
First of all: Thanks for an awezome package. (Goodwill license sent to you)

Problem:
When i try to export a rather sizable website usync failes to export my multinode treepickers. Below a section of my log file.

- Does uSync require newtonsoft v. 10 to work? Will umbraco work with this version?

Seems strange that it only fails on MNTP

Cheers

```
 2017-06-06 09:55:10,782 [P31356/D2/T60] WARN  Jumoo.uSync.Core.Serializers.DataTypeSerializer - Error Serializing System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
File name: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'
   at Jumoo.uSync.Core.Helpers.uSyncValueMapper.GetValueMatchSubstring(String value)
   at Jumoo.uSync.Core.Helpers.uSyncValueMapper.MapToGeneric(String value, Int32 mapId)
   at Jumoo.uSync.Core.Serializers.DataTypeSerializer.SerializePreValues(IDataTypeDefinition item, XElement node)
   at Jumoo.uSync.Core.Serializers.DataTypeSerializer.SerializeCore(IDataTypeDefinition item)
```

**Comment by KevinJump** [comment]
oh - it shouldn't :( 

The latest version is built against Umbraco 7.4 / Netwtonsoft 6.0.8 - which is the same version as 7.5.13, so it shouldn't need updating. I will have a look and see - but check and see if there another package that might have updated Newtonsoft on your build?

**Comment by Ladefuss** [comment]
Cheers Kevin. Seems our own framework needs 8.0.3 which uSynch obviously isn't built against. 
Thanks for your time

**Comment by KevinJump** [comment]
Hi, 

it should still work if the web.config has the range in it, then .net should map the v6 stuff to the v8 version you have. i.e this is the umbraco 7.6.x entry, and usync (targeted at 6.0.8) works with this. 

```  
    <dependentAssembly>
      	<assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
      	<bindingRedirect oldVersion="0.0.0.0-10.0.0.0" newVersion="10.0.0.0" />
      </dependentAssembly>
```
