### ISSUE TITLE
Usync export media fails

### ISSUE THREAD

**Issue by maarten-kieft** [KevinJump/uSync3.0#192]
Hi,

When I perform a full export, the media folder is missing. When I check the logs I see the following

> 2018-09-17 08:53:27,866 [P1680/D26/T34] INFO  Jumoo.uSync.BackOffice.uSyncApplicationEventHandler - Running full Umbraco Export
 2018-09-17 08:53:27,881 [P1680/D26/T34] INFO  Jumoo.uSync.BackOffice.Handlers.DataTypeHandler - Exporting all DataTypes.
 2018-09-17 08:53:34,333 [P1680/D26/T34] INFO  Jumoo.uSync.BackOffice.Handlers.TemplateHandler - Exporting all Templates
 2018-09-17 08:53:37,411 [P1680/D26/T34] INFO  Jumoo.uSync.BackOffice.Handlers.ContentTypeHandler - Exporting all ContentTypes (DocTypes)
 2018-09-17 08:53:48,521 [P1680/D26/T34] INFO  Jumoo.uSync.BackOffice.Handlers.MediaTypeHandler - Exporting all MediaTypes
 2018-09-17 08:53:49,333 [P1680/D26/T34] INFO  Jumoo.uSync.BackOffice.Handlers.LanguageHandler - Exporting all Langauges
 2018-09-17 08:53:49,365 [P1680/D26/T34] INFO  Jumoo.uSync.BackOffice.Handlers.DictionaryHandler - Exporting all Dictionary Items
 2018-09-17 08:53:49,397 [P1680/D26/T34] INFO  Jumoo.uSync.BackOffice.Handlers.MacroHandler - Exporting all Macros
 2018-09-17 08:53:49,427 [P1680/D26/T34] INFO  Jumoo.uSync.Content.MediaHandler - Exporting Media
 2018-09-17 08:53:49,632 [P1680/D26/T34] WARN  Jumoo.uSync.BackOffice.uSyncEvents - Failed to save node: 
 2018-09-17 08:53:49,787 [P1680/D26/T34] WARN  Jumoo.uSync.BackOffice.uSyncEvents - Failed to save node: 
 2018-09-17 08:53:49,865 [P1680/D26/T34] WARN  Jumoo.uSync.Content.ContentHandler - Error saving Media: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\home\site\wwwroot\uSync\data\Media\test-map-wordt-later-verwijderd\aanvraagproces.png\_uSyncMedia'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Jumoo.uSync.Core.Helpers.uSyncMediaFileMover.ExportFile(IMedia item, String folder)
   at Jumoo.uSync.Content.MediaHandler.ExportItem(IMedia item, String path, String root)
 2018-09-17 08:53:49,896 [P1680/D26/T34] WARN  Jumoo.uSync.BackOffice.uSyncEvents - Failed to save node: 
 2018-09-17 08:53:49,927 [P1680/D26/T34] WARN  Jumoo.uSync.Content.ContentHandler - Error saving Media: System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\home\site\wwwroot\uSync\data\Media\test-map-wordt-later-verwijderd\someimage.jpg\_uSyncMedia'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Jumoo.uSync.Core.Helpers.uSyncMediaFileMover.ExportFile(IMedia item, String folder)
   at Jumoo.uSync.Content.MediaHandler.ExportItem(IMedia item, String path, String root)`

... 

> 2018-09-17 :54:08,574 [P1680/D26/T34] INFO  Jumoo.uSync.Content.ContentHandler - Exporting Content
 2018-09-17 08:54:23,124 [P1680/D26/T30] INFO  Umbraco.Web.Scheduling.BackgroundTaskRunner - [Umbraco.Web.Scheduling.IBackgroundTask] Terminating
 2018-09-17 08:54:41,419 [P1680/D27/T58] INFO  Umbraco.Core.MainDom - Acquiring MainDom...
 2018-09-17 08:54:41,435 [P1680/D27/T58] INFO  Umbraco.Core.MainDom - Acquired MainDom.
 2018-09-17 08:54:52,388 [P1680/D27/T58] INFO  Jumoo.uSync.BackOffice.uSyncApplicationEventHandler - Initializing uSync 73
 2018-09-17 08:54:52,388 [P1680/D27/T58] INFO  Jumoo.uSync.BackOffice.uSyncApplicationEventHandler - Firing up uSync
 2018-09-17 08:54:54,607 [P1680/D27/T58] INFO  Jumoo.uSync.Core.uSyncCoreContext - Loading Context (2116ms)
 2018-09-17 08:54:54,685 [P1680/D27/T58] INFO  Jumoo.uSync.BackOffice.uSyncBackOfficeContext - Loading up Sync Handlers : 20
 2018-09-17 08:54:54,717 [P1680/D27/T58] INFO  Jumoo.uSync.Content.ContentTemplateHandler - Content Handler Enabled = True
 2018-09-17 08:54:54,732 [P1680/D27/T58] INFO  Jumoo.uSync.BackOffice.uSyncApplicationEventHandler - Setting up Events default
 2018-09-17 08:54:54,763 [P1680/D27/T58] INFO  Jumoo.uSync.BackOffice.uSyncAction - ### uSync.BackOffice Processed 0 items with 0 changes ###
 2018-09-17 08:54:54,763 [P1680/D27/T58] INFO  Jumoo.uSync.BackOffice.uSyncApplicationEventHandler - uSync Complete (2366ms)
 2018-09-17 08:54:55,029 [P1680/D27/T58] INFO  Umbraco.Web.Search.ExamineEvents - Initializing 
 2018-09-17 08:55:19,987 [P1680/D26/T34] INFO  Jumoo.uSync.BackOffice.uSyncActionLogger - Saving uSync Report: D:\home\site\wwwroot\App_Data\temp\uSync\20180917_085519_Export.config

Any idea what is going wrong? I have the feeling that umbraco executes an restart when I see this logs.

**Comment by KevinJump** [comment]
Hi 

is your media folder on something like azure ?

**Comment by maarten-kieft** [comment]
Yes.

Edit:
aaahhh wait, it might been configured as a virtual directory so thats why it can't find it.

**Comment by maarten-kieft** [comment]
aaahhh wait, it might been configured as a virtual directory so thats why it can't find it.

**Comment by KevinJump** [comment]
ahh ok.

it might also be worth looking at the move media setting in the config :  https://github.com/KevinJump/uSync/blob/v4_master/Jumoo.uSync.Core/Config/uSyncCore.Config#L8

because you don't need to put the actual media files into the usync folder - and can just have usync do the db elements - that might help.

**Comment by maarten-kieft** [comment]
Thanks for the quick replies kevin. I will adjust the config.
