### ISSUE TITLE
Error: An error has occurred. - Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by JohnBergman** [KevinJump/uSync3.0#204]
Doing an import on a different computer; or doing a FULL Import on the computer that has the new changes results in the Object Reference error

The error was happening, so I upgraded to the latest versions on nuget - no change.

The usync tab shows these versions
(uSync.BackOffice 4.0.9.0) (uSync.Core 6.0.9.0) [uSync.Content: 4.1.5.0] [uSync.Snapshots: 1.4.1.0]

Let me know what additional information you need to troubleshoot.

**Here is the log, including the stack trace**

2018-11-21 13:19:00,122 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.uSyncApplicationEventHandler - Running uSync Import: Group = default Folder = ~/uSync/data/ Force = True
 2018-11-21 13:19:00,127 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Running Import: DataType
 2018-11-21 13:19:00,133 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IDataTypeDefinition
 2018-11-21 13:19:00,169 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IDataTypeDefinition
 2018-11-21 13:19:00,206 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IDataTypeDefinition
 2018-11-21 13:19:52,065 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Handler Import Complete: 68 Items 68 changes 0 failures
 2018-11-21 13:19:52,070 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Running Import: Template
 2018-11-21 13:20:17,902 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Handler Import Complete: 38 Items 38 changes 0 failures
 2018-11-21 13:20:17,944 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Running Import: DocumentType
 2018-11-21 13:20:17,950 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:17,976 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,053 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,079 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,119 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,146 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,218 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,254 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,282 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,305 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,328 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,355 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,379 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,399 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,423 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,461 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,490 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,512 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,534 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,559 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,585 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,618 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,691 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,732 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,821 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,868 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,912 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,952 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:18,993 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:19,053 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:19,078 [P15736/D2/T73] INFO  Jumoo.uSync.BackOffice.Logging - Processing a Delete: Umbraco.Core.Models.IContentType
 2018-11-21 13:20:36,200 [P15736/D2/T73] ERROR Jumoo.uSync.BackOffice.Controllers.uSyncApiController - Unhandled controller exception occurred
Sy
 2018-11-21 13:20:36,200 [P15736/D2/T73] ERROR Jumoo.uSync.BackOffice.Controllers.uSyncApiController - Unhandled controller exception occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jumoo.uSync.Core.Serializers.ContentTypeBaseSerializer`1.DeserializeBase(IContentTypeBase item, XElement info)
   at Jumoo.uSync.Core.Serializers.ContentTypeSerializer.DeserializeCore(XElement node)
   at Jumoo.uSync.Core.Serializers.SyncBaseSerializer`1.DeSerialize(XElement node, Boolean forceUpdate)
   at Jumoo.uSync.BackOffice.Handlers.ContentTypeHandler.Import(String filePath, Boolean force)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.Import(IEnumerable`1 syncHandlers, String folder, Boolean checkConfig, Boolean force, String groupName)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.Import(String groupName, String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.Controllers.uSyncApiController.Import(Boolean force)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__3(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()

**Comment by JohnBergman** [comment]
I turned on debug logging based on what I found in a post on our.umbraco.com (<logger name="Jumoo.uSync"><level value="Debug" /></logger>)

I've attached the full log. 
[UmbracoTraceLog.DESKTOP-KD8NI8M.txt](https://github.com/KevinJump/uSync/files/2605538/UmbracoTraceLog.DESKTOP-KD8NI8M.txt)

More Errors were encountered:

 2018-11-21 13:35:06,637 [P33120/D2/T1] DEBUG Jumoo.uSync.Core.Serializers.ContentTypeSerializer - Looking up ContentType by alias
 2018-11-21 13:35:06,734 [P33120/D2/T1] INFO  Jumoo.uSync.BackOffice.uSyncApplicationEventHandler - No Throw errors is set, so uSync won't YSOD
 2018-11-21 13:35:06,749 [P33120/D2/T1] ERROR Jumoo.uSync.BackOffice.uSyncApplicationEventHandler - Error During Setup:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jumoo.uSync.Core.Serializers.ContentTypeBaseSerializer`1.DeserializeBase(IContentTypeBase item, XElement info)
   at Jumoo.uSync.Core.Serializers.ContentTypeSerializer.DeserializeCore(XElement node)
   at Jumoo.uSync.Core.Serializers.SyncBaseSerializer`1.DeSerialize(XElement node, Boolean forceUpdate)
   at Jumoo.uSync.BackOffice.Handlers.ContentTypeHandler.Import(String filePath, Boolean force)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.Import(IEnumerable`1 syncHandlers, String folder, Boolean checkConfig, Boolean force, String groupName)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.Import(String groupName, String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncApplicationEventHandler.Setup()

Followed later by the error logged with the default settings

2018-11-21 13:37:14,288 [P33120/D2/T10] DEBUG Jumoo.uSync.Core.Serializers.ContentTypeSerializer - Looking up ContentType by alias
 2018-11-21 13:37:14,424 [P33120/D2/T10] ERROR Jumoo.uSync.BackOffice.Controllers.uSyncApiController - Unhandled controller exception occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Jumoo.uSync.Core.Serializers.ContentTypeBaseSerializer`1.DeserializeBase(IContentTypeBase item, XElement info)
   at Jumoo.uSync.Core.Serializers.ContentTypeSerializer.DeserializeCore(XElement node)
   at Jumoo.uSync.Core.Serializers.SyncBaseSerializer`1.DeSerialize(XElement node, Boolean forceUpdate)
   at Jumoo.uSync.BackOffice.Handlers.ContentTypeHandler.Import(String filePath, Boolean force)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportFolder(String folder, Boolean force, Dictionary`2 updates)
   at Jumoo.uSync.BackOffice.Handlers.uSyncBaseHandler`1.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.Import(IEnumerable`1 syncHandlers, String folder, Boolean checkConfig, Boolean force, String groupName)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.Import(String groupName, String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.Controllers.uSyncApiController.Import(Boolean force)
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_1.<GetExecutor>b__3(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
-

**Comment by JohnBergman** [comment]
I was able to get around this, but my ask would be to update the exception message to somehow include what is being processed (ie, the alias name, document type, etc) so that it can be narrowed down much faster.

This one appeared to be related to either a control that was created as document qualified and not used; I went through control by control and verified them and whether they were used as well as examined every document type to make sure that the controls in play in the document type were valid.

**Comment by StefanoChiodino** [comment]
I have had the same problem a couple of times. It happens when merging changes in, and it's very hard to find where the problem lies!
