### ISSUE TITLE
Property List Compatibility

### ISSUE THREAD

**Issue by JohnBergman** [KevinJump/uSync3.0#217]
I know this is not necessarily a usync issue, but when we recieve this or any other error, the backoffice usync page stops indicating the status of the import... so the only way to know when it is complete is by looking in the log.

In the mean time; is there a way to nudge usync for these other controls how to serialize their data?

 2019-05-02 18:01:58,317 [P5396/D2/T87] INFO  Umbraco.Core.Publishing.PublishingStrategy - Content 'Has Company Name of Flerish' with Id '5016' has been published.
 2019-05-02 18:01:58,473 [P5396/D2/T87] ERROR Jumoo.uSync.BackOffice.Controllers.uSyncApiController - Unhandled controller exception occurred
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Our.Umbraco.PropertyList.PropertyEditors.PropertyListPropertyValueEditor.ConvertDbToXml(Property property, PropertyType propertyType, IDataTypeService dataTypeService)
   at Umbraco.Core.Services.EntityXmlSerializer.Serialize(IDataTypeService dataTypeService, Property property)
   at Umbraco.Core.Services.EntityXmlSerializer.Serialize(IDataTypeService dataTypeService, IContentBase contentBase, String nodeName)
   at Umbraco.Core.Services.EntityXmlSerializer.Serialize(IContentService contentService, IDataTypeService dataTypeService, IUserService userService, IContent content, Boolean deep)
   at Umbraco.Core.Services.ContentService.<SaveAndPublishDo>b__106_0(IContent c)
   at Umbraco.Core.Persistence.Repositories.ContentPreviewRepository`1.PersistNewItem(ContentPreviewEntity`1 entity)
   at Umbraco.Core.Persistence.UnitOfWork.ScopeUnitOfWork.Commit(Action`1 transactionCompleting)
   at Umbraco.Core.Services.ContentService.SaveAndPublishDo(IContent content, Int32 userId, Boolean raiseEvents)
   at Umbraco.Core.Services.ContentService.Umbraco.Core.Services.IContentServiceOperations.SaveAndPublish(IContent content, Int32 userId, Boolean raiseEvents)
   at Umbraco.Core.Services.ContentService.SaveAndPublishWithStatus(IContent content, Int32 userId, Boolean raiseEvents)
   at Jumoo.uSync.Core.Serializers.ContentSerializer.PublishOrSave(IContent item, Boolean published, Boolean raiseEvents)
   at Jumoo.uSync.Core.Serializers.ContentSerializer.DesearlizeSecondPass(IContent item, XElement node)
   at Jumoo.uSync.Content.ContentHandler.ImportSecondPass(String file, IContent item)
   at Jumoo.uSync.Content.BaseContentHandler`1.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.Import(IEnumerable`1 syncHandlers, String folder, Boolean checkConfig, Boolean force, String groupName)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.Import(String groupName, String folder, Boolean force)
   at Jumoo.uSync.BackOffice.uSyncBackOfficeContext.ImportAll(String folder, Boolean force)
   at Jumoo.uSync.BackOffice.Controllers.uSyncApiController.Import(Boolean force)
   at lambda_method(Closure , Object , Object[] )

**Comment by JohnBergman** [comment]
Here is an example of the content.config file that is not read back in


[content.zip](https://github.com/KevinJump/uSync/files/3139486/content.zip)
