### ISSUE TITLE
Media Images not importing

### ISSUE THREAD

**Issue by KevinJump** [KevinJump/uSync3.0#45]
Migrated issue https://github.com/KevinJump/jumps.umbraco.usync/issues/61 from old repo:

@victorcea87

> Hi,
> 
> I'm having a lot of problems with the images importing with uSync. I'm doing what Kevin Jump said me, it means put the media importing to false and leaving the images in the root media folder (in the uSync>Data>Media I just have the configs). The problem what I'm having now is that I'm doing a full import and the images are created in the media tab in Umbraco but they are not visible, is very strange, I can see the item in the media tab but when I access the image doesn't appear and the website doesn't charge them neither.
> 
> Any thoughts?
> 
> Thanks!
> 
> I can see as well that when uSync imports the images a part of the problem that it's importing them in wrong way is changing all the config files from each media in uSync folder to remove the src href to the media folder and leave it empty :( it's frustrating.

**Comment by KevinJump** [comment]
Hi, 

I can't reproduce on a clean install of umbraco just to clarify

this is just stuff in the media section. 
- /media folder copied over. 
- import of media items from the usync/data/media folder.
- the usync files in that folder have the /media/ paths in them ? 
- media is either using image cropper or image as the control? 

version of usync??

**Comment by victorcea87** [comment]
Hi Kevin,

Now usync is throwing this error:

![image](https://cloud.githubusercontent.com/assets/2836729/15071427/c0e4b7f8-138b-11e6-8e66-5fe1c3cf3b1b.png)

Is not too much explanatory I'm afraid...any idea?

**Comment by KevinJump** [comment]
hi - anything in the logs ?

**Comment by victorcea87** [comment]
It's in azure so I'm not sure how to check the logs :S

**Comment by victorcea87** [comment]
Just a second, I got them and I can see this:

![image](https://cloud.githubusercontent.com/assets/2836729/15072767/65cc2522-1395-11e6-9cc3-09e884f5b384.png)

**Comment by KevinJump** [comment]
Hi

i need to see a bit further down that error, to she where usync was when it was called. (are their any Jumoo.uSync lines below?

**Comment by victorcea87** [comment]
![image](https://cloud.githubusercontent.com/assets/2836729/15076188/b347d162-13a8-11e6-971d-33b1cf9fee44.png)

**Comment by victorcea87** [comment]
By the way, I will take profit to this conversation to ask you if there is any option to see the progress of uSync when is importing at the start, In my case it take ages to end (and most times with error). And while uSync is putting the data in SQL the site doesn't work, it returns a timeout...(is Azure)

**Comment by victorcea87** [comment]
I have seen other errors:

ERROR Umbraco.Web.Scheduling.KeepAlive - Failed (at "http://localhost:80/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 127.0.0.1:80
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.KeepAlive.<PerformRunAsync>d__4.MoveNext()
 2016-05-06 16:11:42,435 [P6912/D2/T25] ERROR Umbraco.Web.Scheduling.ScheduledPublishing - Failed (at "http://localhost:80/umbraco").
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 127.0.0.1:80
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Web.Scheduling.ScheduledPublishing.<PerformRunAsync>d__5.MoveNext()
 2016-05-06 16:12:42,444 [P6912/D2/T25] ERROR Umbraco.Web.Scheduling.ScheduledPublishing - Failed (at "http://localhost:80/umbraco").

**Comment by victorcea87** [comment]
I have discovered another thing. The undefined error only happens in Azure, locally it works fine. And the last comment in Azure logs is:

Jumoo.uSync.BackOffice.uSyncApplicationEventHandler - Running Import Report

I have activated the Debug logs for uSync and after the line before it checks all the elements with no errors! So...the only thing that could be is...timeout. The operation takes around 40 seconds so I'm afraid that is a timeout issue, you know how to avoid it? (The result a part of the undefined error is that the screen is keeping with the 3 blue points forever...)

Logs:

![image](https://cloud.githubusercontent.com/assets/2836729/15080419/44a20d84-13be-11e6-8730-e44a596417e5.png)

**Comment by KevinJump** [comment]
Hi 

I am going to have to have a look at this on azure at some point, the strange thing with the logs is how the media serializer just keeps looping. someone reported a similar problem with the localgov starter kit package which was importing its sample content multiple times, I am not 100% sure what is causing it to do that, but i will have a look into it.

**Comment by florinlazau** [comment]
Hi,
How can i see log files in azure?
When I try to import i get this "nice" error.
![image](https://cloud.githubusercontent.com/assets/13690344/21993713/fd1eca3a-dc24-11e6-92c9-0e1715488fae.png)

Thanks

**Comment by KevinJump** [comment]
Hi 

If you can get to the app_data/logs folder in azure then usync will have logged any errors in the umbraco log file. 
or 
you can install the Diplo Log Viewer to see these in the back office. 
or
If you open chrome dev tools (right click page inspect) open the network tab and reload the page, then you should see (in red) the request that fails, you might be able to explore to the error within chrome. 

Kevin
